import Button from '@/components/Button';
import Head from 'next/head';
import React from 'react';
import ArrowIcon from '../assets/ArrowIcon.svg';
// import { ReactComponent as ArrowIcon } from '../assets/ArrowIcon.svg';

console.log(ArrowIcon);

const Home = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta
        content="Generated by create next app"
        name="description"
      />
      <meta
        content="width=device-width, initial-scale=1"
        name="viewport"
      />
      <link
        href="/favicon.ico"
        rel="icon"
      />
    </Head>

    <Button.Default
      // icon={<ArrowIcon />}
      icon={ArrowIcon}
      onClick={() => console.log(5)}
      size="large"
    >
      Label
    </Button.Default>

    <Button.Outline
      size="large"
    >
      Label
    </Button.Outline>

  </div>
);

export default Home;
